---

- name: Configure Django Web Server
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install python3-venv package
      ansible.builtin.apt:
        name: python3-venv
        state: present

    - name: Create a virtual environment
      ansible.builtin.command: python3 -m venv env
      args:
        chdir: /home/ubuntu
      changed_when: false

    - name: Activate the virtual environment as root
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
      args:
        chdir: /home/ubuntu
        executable: /bin/bash
      changed_when: false
      become_user: root

    - name: Install python3-pip package
      ansible.builtin.apt:
        name: python3-pip
        state: present
      changed_when: false

    - name: Clone django-demo repository
      ansible.builtin.git:
        repo: https://github.com/genialis/django-demo
        dest: /home/ubuntu/django-demo
        update: true
        version: main
        force: true

    - name: Install requirements from django-demo
      ansible.builtin.pip:
        requirements: /home/ubuntu/django-demo/requirements.txt
        virtualenv: /home/ubuntu/env

    - name: Install Gunicorn
      ansible.builtin.pip:
        name: gunicorn
        virtualenv: /home/ubuntu/env

    - name: Set variables for template task
      ansible.builtin.set_fact:
        server_public_ip: "{{ server_public_ip }}"

    - name: Overwrite settings.py file
      ansible.builtin.template:
        src: settings.py.j2
        dest: /home/ubuntu/django-demo/demo/settings.py
        owner: root
        group: root
        mode: "0644"
        force: true

    - name: Install Supervisor
      ansible.builtin.apt:
        name: supervisor
        state: present

    - name: Set variables for gunicorn.conf template
      ansible.builtin.set_fact:
        directory_path: "/home/ubuntu"
        log_directory: "/var/log/gunicorn"
        project_name: "django-demo"
        app_name: "demo"

    - name: Create gunicorn.conf file
      ansible.builtin.template:
        src: gunicorn.conf.j2
        dest: /etc/supervisor/conf.d/gunicorn.conf
        owner: root
        group: root
        mode: "0644"
        force: true

    - name: Create /var/log/gunicorn directory
      ansible.builtin.file:
        path: /var/log/gunicorn
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Run supervisorctl reread
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
        supervisorctl reread
      changed_when: false

    - name: Run supervisorctl update
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
        supervisorctl update
      changed_when: false

    - name: Restart supervisor
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
        /usr/bin/systemctl restart supervisor
      changed_when: false

    - name: Overwrite default Nginx configuration
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: ubuntu
        group: ubuntu
        mode: "0644"
        force: true

    - name: Reload Nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Run migrate command
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
        python3 manage.py migrate
      args:
        chdir: /home/ubuntu/django-demo
        executable: /bin/bash
      changed_when: false

    - name: Run collectstatic command
      ansible.builtin.shell: |
        source /home/ubuntu/env/bin/activate
        python3 manage.py collectstatic --noinput
      args:
        chdir: /home/ubuntu/django-demo
        executable: /bin/bash
      changed_when: false

    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
