name: Ansible Playbook Testing

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test_playbooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Test Playbooks
        run: ansible-playbook configure_django_web_server.yml